site_name: Project Tetsuo
repo_url: https://github.com/tetsuo-dev/tetsuo.dev-code
repo_name: tetsuo-dev/code
plugins:
  - search
  - offline
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: slate
    - primary: amber
    - accent: amber
    # Palette toggle for light mode
    - scheme: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
