site_name: Project Tetsuo
repo_url: https://github.com/tetsuo-dev/tetsuo.dev-code
repo_name: tetsuo-dev/code
plugins:
  - search
  - offline
theme:
  name: material
  features:
    # - content.action.edit
    # - content.action.view
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
